// <auto-generated />
using MealMatch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealMatch.Migrations
{
    [DbContext(typeof(MealMatchDbContext))]
    [Migration("20260927105648_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MealMatch.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hoeveelheid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceptID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceptID");

                    b.ToTable("Ingredienten");
                });

            modelBuilder.Entity("MealMatch.Models.Recept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BereidingstijdMinuten")
                        .HasColumnType("int");

                    b.Property<string>("Bereidingswijze")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opmerking")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Personen")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recepten");
                });

            modelBuilder.Entity("MealMatch.Models.Ingredient", b =>
                {
                    b.HasOne("MealMatch.Models.Recept", null)
                        .WithMany("Ingredienten")
                        .HasForeignKey("ReceptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MealMatch.Models.Recept", b =>
                {
                    b.Navigation("Ingredienten");
                });
#pragma warning restore 612, 618
        }
    }
}
