// <auto-generated />
using MealMatch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealMatch.Migrations
{
    [DbContext(typeof(MealMatchDbContext))]
    [Migration("20261009121400_IngredientOpschonen")]
    partial class IngredientOpschonen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MealMatch.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredienten");
                });

            modelBuilder.Entity("MealMatch.Models.Recept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BereidingstijdMinuten")
                        .HasColumnType("int");

                    b.Property<string>("Bereidingswijze")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opmerking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Personen")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Recepten");
                });

            modelBuilder.Entity("MealMatch.Models.ReceptIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hoeveelheid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ReceptId");

                    b.ToTable("ReceptIngredienten");
                });

            modelBuilder.Entity("MealMatch.Models.ReceptIngredient", b =>
                {
                    b.HasOne("MealMatch.Models.Ingredient", "Ingredient")
                        .WithMany("ReceptIngredienten")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealMatch.Models.Recept", "Recept")
                        .WithMany("ReceptIngredienten")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("MealMatch.Models.Ingredient", b =>
                {
                    b.Navigation("ReceptIngredienten");
                });

            modelBuilder.Entity("MealMatch.Models.Recept", b =>
                {
                    b.Navigation("ReceptIngredienten");
                });
#pragma warning restore 612, 618
        }
    }
}
